"""behavior domain

Revision ID: 0ba0ff15b0f6
Revises: ff5f6770702b
Create Date: 2026-10-04 16:39:13.442206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba0ff15b0f6'
down_revision: Union[str, Sequence[str], None] = 'ff5f6770702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_labels',
    sa.Column('activity_label_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_category', sa.Enum('Entertainment', 'Study', 'Health', 'Work', 'Travel', 'Social', 'Rest', 'Admin', name='primary_category'), nullable=False),
    sa.Column('activity_label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_label_id'),
    sa.UniqueConstraint('user_id', 'primary_category', 'activity_label', name='uq_activity_labels_user_category_label')
    )
    op.create_index(op.f('ix_activity_labels_user_id'), 'activity_labels', ['user_id'], unique=False)
    op.create_table('behavior_context_tags',
    sa.Column('behavior_context_tag_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_category', sa.Enum('Entertainment', 'Study', 'Health', 'Work', 'Travel', 'Social', 'Rest', 'Admin', name='primary_category'), nullable=False),
    sa.Column('context_tag', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('behavior_context_tag_id'),
    sa.UniqueConstraint('user_id', 'primary_category', 'context_tag', name='uq_context_tags_user_category_tag')
    )
    op.create_index(op.f('ix_behavior_context_tags_user_id'), 'behavior_context_tags', ['user_id'], unique=False)
    op.create_table('behaviors',
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_category', sa.Enum('Entertainment', 'Study', 'Health', 'Work', 'Travel', 'Social', 'Rest', 'Admin', name='primary_category'), nullable=False),
    sa.Column('activity_label_id', sa.UUID(), nullable=True),
    sa.Column('energy_level', sa.Enum('High', 'Medium', 'Low', name='energy_level'), nullable=True),
    sa.Column('emotion_state', sa.Enum('Calm', 'Stressed', 'Neutral', 'Irritated', name='emotion_state'), nullable=True),
    sa.Column('focus_state', sa.Enum('Focused', 'Neutral', 'Distracted', name='focus_state'), nullable=True),
    sa.Column('environment', sa.Enum('Home', 'College', 'Library', 'PG', 'Travel', 'Gym', 'Office', name='environment'), nullable=True),
    sa.Column('precision', sa.Enum('LOW', 'HIGH', name='behavior_precision'), server_default='HIGH', nullable=False),
    sa.Column('source', sa.Enum('manual', 'live_tracking', 'gap_fill', 'edit', 'from_task', name='behavior_source'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_label_id'], ['activity_labels.activity_label_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('behavior_id')
    )
    op.create_index(op.f('ix_behaviors_user_id'), 'behaviors', ['user_id'], unique=False)
    op.create_index('ix_behaviors_user_start_time', 'behaviors', ['user_id', 'start_time'], unique=False)
    op.execute(
        """
        ALTER TABLE behaviors
        ADD CONSTRAINT ex_behaviors_no_overlap_per_user
        EXCLUDE USING gist (
            user_id WITH =,
            tstzrange(start_time, end_time, '[)') WITH &&
        )
        WHERE (deleted_at IS NULL)
        """
    )
    op.create_table('behavior_context_tag_map',
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('behavior_context_tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_context_tag_id'], ['behavior_context_tags.behavior_context_tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.behavior_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('behavior_id', 'behavior_context_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('behavior_context_tag_map')
    op.drop_index('ix_behaviors_user_start_time', table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_user_id'), table_name='behaviors')
    op.drop_table('behaviors')
    op.drop_index(op.f('ix_behavior_context_tags_user_id'), table_name='behavior_context_tags')
    op.drop_table('behavior_context_tags')
    op.drop_index(op.f('ix_activity_labels_user_id'), table_name='activity_labels')
    op.drop_table('activity_labels')
    for type_name in (
        'behavior_precision',
        'behavior_source',
        'environment',
        'focus_state',
        'emotion_state',
        'energy_level',
        'primary_category',
    ):
        op.execute(f'DROP TYPE IF EXISTS {type_name}')
    op.execute('DROP EXTENSION IF EXISTS btree_gist')
