"""tasks

Revision ID: 2fdfebd61def
Revises: 0ba0ff15b0f6
Create Date: 2026-10-04 18:30:50.975233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

PRIMARY_CATEGORY = postgresql.ENUM(
    'Entertainment', 'Study', 'Health', 'Work', 'Travel', 'Social', 'Rest', 'Admin',
    name='primary_category', create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = '2fdfebd61def'
down_revision: Union[str, Sequence[str], None] = '0ba0ff15b0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('primary_category', PRIMARY_CATEGORY, nullable=False),
    sa.Column('activity_label_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_label_id'], ['activity_labels.activity_label_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_user_start_time', 'tasks', ['user_id', 'start_time'], unique=False)
    op.create_table('task_context_tag_map',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('behavior_context_tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_context_tag_id'], ['behavior_context_tags.behavior_context_tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'behavior_context_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_context_tag_map')
    op.drop_index('ix_tasks_user_start_time', table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
